#!/bin/sh /etc/rc.common
# Srun Authentication Service Init Script

START=99
STOP=10

USE_PROCD=1

start_service() {
    config_load srun
    local enabled
    local auto_login
    
    config_get_bool enabled basic enabled 0
    config_get_bool auto_login basic auto_login 1
    
    [ "$enabled" = "1" ] || return 0
    
    procd_open_instance
    procd_set_param command /bin/sh -c "sleep 10 && /usr/bin/srun-auth login"
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    /usr/bin/srun-auth logout
}

reload_service() {
    stop
    start
}
